[ERROR][2023-12-29 10:33:22,034][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:35:26,902][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:36:32,638][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:39:58,456][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:43:30,866][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:46:49,670][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:50:26,718][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:52:36,070][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:53:54,239][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:57:10,552][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 10:58:32,679][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:02:22,551][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:03:49,071][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:04:49,345][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:07:23,651][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:11:59,719][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:14:57,076][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:16:35,819][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:17:25,862][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:21:35,510][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:23:43,664][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:29:04,870][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:30:06,423][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 11:31:25,046][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 13:50:28,390][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 13:53:43,979][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 13:59:43,580][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:04:18,851][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:06:16,558][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:08:42,332][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:11:56,141][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:12:24,173][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:13:20,757][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:15:43,689][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:16:41,340][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:17:22,062][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:22:25,288][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:26:24,429][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:27:04,002][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:37:25,555][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:41:14,805][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:50:35,084][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 14:53:18,637][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:33:16,969][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:34:55,144][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:36:18,084][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:37:47,259][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:39:17,691][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:40:56,003][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:43:52,250][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:45:19,474][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 15:48:29,817][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:03:45,971][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:06:52,270][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:08:14,160][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:09:10,953][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:09:54,368][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:11:26,300][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:12:16,178][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:16:03,312][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:19:30,152][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:22:46,091][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:28:00,295][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:29:11,528][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:30:19,321][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:34:29,065][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 16:38:39,121][runTestCases_service.py:585]--报错信息：Exception(),报错的行号:583
[ERROR][2023-12-29 21:02:02,854][generateAutoTestCases_service.py:155]--数据异常，请查看文档sheet页[前端功能页面配置]!
