[ERROR][2023-12-26 10:16:53,635][runTestCases_service.py:319]--报错信息：gaierror(11001, 'getaddrinfo failed'),报错的行号:317
